<?php

declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Tweakwise\TweakwiseJs\ViewModel\Search;

/** @var Template $block */

/** @var Search $viewModel */
$viewModel = $block->getViewModel();

if ($viewModel->isAutoInitEnabled()) {
    return;
}

$cid = $viewModel->getStoreRootCategory();
?>

<script>
    window.addEventListener('twn.starter.ready', function () {
        const params = new URLSearchParams(location.search);
        tweakwiseListerPage({
            query: params.get("tn_q"),
            output: "#tweakwise-output",
            cid: "<?= $block->escapeJs((string) $cid) ?>"
        });
    });
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript(); ?>
