<?php
declare(strict_types = 1);

use Magento\Framework\View\Element\Template;
use Tweakwise\TweakwiseJs\ViewModel\Base;

/** @var Template $block */
/** @var Base $viewModel */
$viewModel = $block->getData('view_model');
$language = (string) $viewModel->getLanguage();
$uiLanguage = (string) $viewModel->getUiLanguage();
?>

<script>
    window.tweakwiseFailover = function (src) {
        const script = document.createElement('script');
        script.async = true;
        script.src = src;
        document.head.appendChild(script);
    };
    window['twn-starter-config'] = window['twn-starter-config'] || {};
    window['twn-starter-config'].on = window['twn-starter-config'].on || {};
    <?php if ($language !== ''): ?>
    window['twn-starter-config'].lang = '<?= $block->escapeJs($language) ?>';
    <?php endif; ?>
    <?php if ($uiLanguage !== ''): ?>
    window['twn-starter-config'].ui = window['twn-starter-config'].ui || {};
    window['twn-starter-config'].ui.lang = '<?= $block->escapeJs($uiLanguage) ?>';
    <?php endif; ?>
</script>

