<?php
declare(strict_types = 1);

?>

<script>
    window.tweakwiseFailover = function (src) {
        const script = document.createElement('script');
        script.async = true;
        script.src = src;
        document.head.appendChild(script);
    };
    window['twn-starter-config'] = window['twn-starter-config'] || {};
    window['twn-starter-config'].on = window['twn-starter-config'].on || {};
    window['twn-starter-config'].auto = false;
    window.addEventListener('twn.starter.ready', function () {
        window['twn-starter-ready'] = true;
    });
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript(); ?>
