<?php

declare(strict_types=1);

use Magento\Catalog\Block\Category\View;
use Tweakwise\TweakwiseJs\ViewModel\Merchandising;

/** @var View $block */

/** @var Merchandising $viewModel */
$viewModel = $block->getViewModel();
$cid = $viewModel->getTweakwiseId((int) $block->getCurrentCategory()->getId());
?>

<script>
    window.addEventListener('twn.starter.ready', function () {
        tweakwiseListerPage({
            cid: "<?= $block->escapeJs($cid) ?>",
            output: "#tweakwise-output"
        });
    });
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript(); ?>
