<?php
declare(strict_types = 1);

use Magento\Catalog\Block\Category\View;
use Tweakwise\TweakwiseJs\ViewModel\Merchandising;

/** @var View $block */

/** @var Merchandising $viewModel */
$viewModel = $block->getViewModel();
$cid = $viewModel->getTweakwiseId((int) $block->getCurrentCategory()->getId());
?>

<script>
    (function () {
        function init() {
            tweakwiseListerPage({
                cid: "<?= $block->escapeJs($cid) ?>",
                output: "#tweakwise-output"
            });
        }

        if (window['twn-starter-ready']) {
            init();
        } else {
            window.addEventListener('twn.starter.ready', init);
        }
    }());
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript(); ?>

