<script>
    window.addEventListener('private-content-loaded', function (event) {
        getSectionNames().forEach(sectionName => {
            const twEvents = event.detail.data[sectionName];

            if (twEvents.tweakwise_events) {
                sendTweakwiseEvents(twEvents.tweakwise_events, sectionName)
            }
        });
    });
</script>
<?php if (isset($hyvaCsp)) $hyvaCsp->registerInlineScript(); ?>
