<?php

declare(strict_types = 1);

use Magento\Catalog\Block\Product\View;
use Tweakwise\TweakwiseJs\ViewModel\Event;

/** @var View $block */

/** @var Event $eventViewModel */
$eventViewModel = $block->getViewModel();
?>
<script>
    pushEvent({
        event: 'purchase',
        data: {
            profileKey: getProfileKey(),
            productKeys: <?= $eventViewModel->getOrderProductIds() ?>,
            revenue: <?= $eventViewModel->getPurchaseRevenue() ?>
        }
    });
</script>
