<?php

declare(strict_types = 1);

use Magento\Catalog\Block\Product\View;
use Tweakwise\TweakwiseJs\ViewModel\Event;

/** @var View $block */

/** @var Event $eventViewModel */
$eventViewModel = $block->getViewModel();
?>
<script>
    pushEvent({
        event: 'productView',
        data: {
            profileKey: getProfileKey(),
            productKey: '<?= $eventViewModel->getTweakwiseId((int)$block->getProduct()->getId()) ?>'
        }
    });
</script>
