name: GrumPHP
on: [push]
jobs:
  linter:
    strategy:
      matrix:
        image: [
          'srcoder/development-php:php82-fpm'
        ]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GITLAB_SSH_KEY }}
      - name: Add GitLab host key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -t rsa,ed25519,ecdsa git.emico.io >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
      - name: Debug SSH key
        run: ssh-add -l
      - name: Test GitLab SSH
        run: ssh -vvv git@git.emico.io || true
      - name: GrumPHP
        run: |
          composer2 config http-basic.repo.magento.com ${{ secrets.MAGENTO_USERNAME }} ${{ secrets.MAGENTO_PASSWORD }}
          composer2 install --dev --prefer-dist --no-scripts --no-progress --optimize-autoloader --no-interaction -vvv
          composer2 show
          vendor/bin/grumphp run --tasks=phpmd,phpcs,xmllint,phplint,composer --no-interaction
        shell: bash
